### ISSUE TITLE
有几个项目无法运行

### ISSUE THREAD

**Issue by minliacom** [open-hand/hzero#4]
有没有一个运行的顺序说明, 现在按照

register
config
gateway
gateway-helper
iam
admin
这个顺序运行后出现几个问题, 请帮忙解答一下.
register项目正常
iam项目正常

config项目出现这个问题, 

org.hzero.boot.admin.exception.ServiceRegisterException: Register to [hzero-admin] server failed!
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$register$2(AdminAutoRegistration.java:135) ~[hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$retryAlwaysUntilSuccess$1(AdminAutoRegistration.java:113) ~[hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_252]
Caused by: org.hzero.boot.admin.exception.TransportException: request [hzero-admin|ALL_INSTANCES] failed
	at org.hzero.boot.admin.transport.AdminTransport.requestAdmin(AdminTransport.java:65) ~[hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.hzero.boot.admin.transport.AdminTransport.transport(AdminTransport.java:44) ~[hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$register$2(AdminAutoRegistration.java:133) ~[hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	... 4 common frames omitted

admin项目出现以下异常

org.hzero.boot.admin.exception.ServiceRegisterException: Register to °hzero-admin§ server failed!
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$register$2(AdminAutoRegistration.java:135) ¨°hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE§
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$retryAlwaysUntilSuccess$1(AdminAutoRegistration.java:113) ¨°hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE§
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ¨°na:1.8.0_252§
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ¨°na:1.8.0_252§
	at java.lang.Thread.run(Thread.java:748) ¨°na:1.8.0_252§
Caused by: org.hzero.boot.admin.exception.TransportException: request °hzero-adminùALL_INSTANCES§ failed
	at org.hzero.boot.admin.transport.AdminTransport.requestAdmin(AdminTransport.java:65) ¨°hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE§
	at org.hzero.boot.admin.transport.AdminTransport.transport(AdminTransport.java:44) ¨°hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE§
	at org.hzero.boot.admin.AdminAutoRegistration.lambda$register$2(AdminAutoRegistration.java:133) ¨°hzero-boot-admin-1.4.0.RELEASE.jar:1.4.0.RELEASE§
	... 4 common frames omitted

gateway项目出来了这个问题: 

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultValidator' defined in class path resource [org/springframework/boot/autoconfigure/validation/ValidationAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@15624129 has not been refreshed yet
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1694) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:819) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:725) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 23 common frames omitted
Caused by: java.lang.IllegalStateException: org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext@15624129 has not been refreshed yet
	at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1074) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.GenericApplicationContext.getAutowireCapableBeanFactory(GenericApplicationContext.java:308) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:283) ~[spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]

谢谢你们的努力

**Comment by XCXCXCXCX** [comment]
1. hzero-register hzero-config hzero-admin
2. hzero-iam 
3. other

**Comment by hzeroseeker** [comment]
可以参考文档，里面补充了顺序：https://open.hand-china.com/document-center/doc/product/10067/10032?doc_id=6335

**Comment by minliacom** [comment]
太棒了 我试试先

**Comment by minliacom** [comment]
太好了  可以运行了 感谢感谢!
